### ISSUE TITLE
can't install with zend farmework 3.0.1

### ISSUE THREAD

**Issue by zaherkassem** [neilime/zf-assets-bundle#1]
i can't install this with zend framework 3.0.1 that need zend--config v2.6.0:

  - Installation request for neilime/zf-assets-bundle 0.0.1 -> satisfiable by neilime/zf-assets-bundle[0.0.1].
    - Conclusion: remove zendframework/zend-config 2.6.0
    - zendframework/zendframework 3.0.0 requires zendframework/zend-config ^2.6 -> satisfiable by zendframework/zend-config[2.6.0].
    - zendframework/zendframework 3.0.0 requires zendframework/zend-config ^2.6 -> satisfiable by zendframework/zend-config[2.6.0].
    - Conclusion: don't install zendframework/zend-config 2.6.0
    - Installation request for zendframework/zendframework 3.0.* -> satisfiable by zendframework/zendframework[3.0.0].

**Comment by zaherkassem** [comment]
hi, 
how are you ? 
any news with this issue  ? did you fix it ? 

thanks

**Comment by neilime** [comment]
Hi, sorry to answer so late.

The new version (https://github.com/neilime/zf-assets-bundle/releases/tag/v0.0.2) requires same versions as zendframework.

**Comment by zaherkassem** [comment]
thank you so much
