### ISSUE TITLE
Generate new production cached file is some asset has been update

### ISSUE THREAD

**Issue by txusma23** [neilime/zf-assets-bundle#23]
Hi,

I have a personal very old project developed with ZF2, and some weeks ago I discovered your module. So, my comment/idea is really for the zf2-assets-bundle but as that repository is read-only now, I post my idea/comment here. 

I'm not really sure if I understand the expected behavior of the module in the 'production' environment. I would expect that a new cached file for an specific action was generated if some of the asset files used in that action had been modified. However, that doesn't seems the case. Should I set a new 'lastModifiedTime' in the options file, every time I modified an asset?

I think that my idea (if you consider interesting) can be achieved by modifying the 'hasProductionCachedAssetFiles' in 'AssetFilesCacheManager' class, to check, not only if the file exists but also if some asset has been updated from the last time we cached the production cached file.

Thank you very much for your help and for your generous effort,

Best regards,

**Comment by neilime** [comment]
Hi @txusma23,;

Maybe this wiki page should help to understand the production behavior: https://github.com/neilime/zf-assets-bundle/wiki/Usage-for-%22development---production%22-environment

Please let me know

**Comment by txusma23** [comment]
Dear Emilien, 

thank you very much. Now everything is clear.

Best regards,
